
variable "cpus" {
  type    = string
  default = "2"
}

variable "disk_size" {
  type    = string
  default = "40960"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "hostname" {
  type    = string
  default = "bionic64"
}

variable "http_proxy" {
  type    = string
  default = ""
}

variable "https_proxy" {
  type    = string
  default = ""
  // ki bch nkhdm maa brcha makinet nwali nbdl mara whda
}


variable "iso_checksum" {
  type    = string
  default = "f5cbb8104348f0097a8e513b10173a07dbc6684595e331cb06f93f385d0aecf6"
  // default = "6c647b1ab4318e8c560d5748f908e108be654bad1e165f7cf4f3c1fc43995934"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_name" {
  type    = string
  default = "ubuntu-18.04.6-server-amd64.iso"
}

variable "iso_path" {
  type    = string
  default = "iso"
}

variable "iso_url" {
  type    = string
  default= "https://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.6-server-amd64.iso"
  // default = "https://releases.ubuntu.com/18.04/ubuntu-18.04.6-live-server-amd64.iso"
}

variable "memory" {
  type    = string
  default = "1024"
}

variable "no_proxy" {
  type    = string
  default = ""
}

variable "preseed" {
  type    = string
  default = "preseed.cfg"
}

variable "ssh_fullname" {
  type    = string
  default = "ubuntu"
}

variable "full_name" {
  type = string
  default = "ubuntu"
}
variable "ssh_password" {
  type    = string
  default = "ubuntu"
}

variable "ssh_username" {
  type    = string
  default = "ubuntu"
}

variable "update" {
  type    = string
  default = "true"
}

variable "version" {
  type    = string
  default = "0.1"
}

variable "virtualbox_guest_os_type" {
  type    = string
  default = "Ubuntu_64"
}

variable "vm_name" {
  type    = string
  default = "ubuntu-18.04-4"
}

variable "home" {
  type    = string
  default = ""
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command = [
    "<esc><esc><enter><wait>",
    "/install/vmlinuz noapic ",
    "initrd=/install/initrd.gz ",
    "install auto=true priority=critical preseed/url=http://172.20.10.5:{{.HTTPPort}}/preseed.cfg<enter>",
    // "append auto=true priority=critical preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg",
    "debian-installer=fr_FR auto locale=fr_FR kbd-chooser/method=fr ",
    "hostname=${var.hostname} ",
    "grub-installer/bootdev=/dev/sda<wait> ",
    "fb=false debconf/frontend=noninteractive ",
    "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=fr",
    "keyboard-configuration/variant=FR console-setup/ask_detect=false ",
    "packer-plugin-virtualbox_v1.0.5_x5.0_windows_amd64.exe",
    "passwd/user-fullname=${var.ssh_fullname} ",
    "passwd/user-password=${var.ssh_password} ",
    "passwd/user-password-again=${var.ssh_password} ",
    "passwd/username=${var.ssh_username} ",
    "<wait><enter>"

  //           "<esc><esc><enter><wait>",
  //           "/install/vmlinuz noapic ",
  //           "initrd=/install/initrd.gz ",
  //           "preseed/url=http:///10.2.245.39:8000/preseed.cfg ",
  //           "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
  //           "hostname={} ",
  //           "grub-installer/bootdev=/dev/sda<wait> ",
  //           "fb=false debconf/frontend=noninteractive ",
  //           "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
  //           "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
  //           "passwd/user-fullname=${var.full_name} ",
  //           "passwd/user-password=${var.ssh_password} ",
  //           "passwd/user-password-again=${var.ssh_password} ",
  //           "passwd/username=${var.ssh_username} ",
  //           "--<enter>"
  ]

  disk_size               = "${var.disk_size}"
  guest_os_type           = "${var.virtualbox_guest_os_type}"
  hard_drive_interface    = "sata"
  headless                = "${var.headless}"
  http_directory          = "./http"
  iso_checksum            = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_urls                = [
    "${var.iso_url}"
  ]
  output_directory        = "output3" #nhotha f var w naadiha fl build command
  shutdown_command        = "echo '${var.ssh_password}'|sudo -S shutdown -P now" #nrodha sensitive
  ssh_username            = "${var.ssh_username}"
  ssh_password            = "${var.ssh_password}"
  ssh_wait_timeout        = "10000s"
  guest_additions_mode    = "disable"
  vboxmanage             = [
    ["modifyvm", "{{ .Name }}", "--audio", "none"], 
    ["modifyvm", "{{ .Name }}", "--usb", "off"], 
    #vram: c quoi 
    ["modifyvm", "{{ .Name }}", "--vram", "12"], #variable
    ["modifyvm", "{{ .Name }}", "--vrde", "off"], 
    // ["modifyvm", "{{ .Name }}", "--nictype1", "virtio"], 
    ["modifyvm", "{{.Name}}", "--nic1", "bridged"],
    ["modifyvm", "{{.Name}}", "--bridgeadapter1", "Intel(R) Wi-Fi 6 AX201 160MHz"],
    ["modifyvm", "{{ .Name }}", "--memory", "${var.memory}"], 
    ["modifyvm", "{{ .Name }}", "--cpus", "${var.cpus}"],
    // ["modifyvm", "{{ .Name }}", "--natpf1", "guestssh,tcp,,2236,,22"]
  ]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "${var.vm_name}"
  format                  = "ova"
}





build {
  sources = ["source.virtualbox-iso.autogenerated_1"]
  //   provisioner "file" {
  //   source      = "script/configure-network.sh"
  //   destination = "/tmp/configure-network.sh"
  // }

  // provisioner "shell" {
  //   inline = ["sudo bash /tmp/configure-network.sh"]
  // }

  // provisioner "shell"{
  //   inline = ["sudo apt update",
  //   "sudo apt -qq -y install software-properties-common git ansible network-manager 2>&1 >/dev/null",
  //   "sed -i s/ens3/enp1s0/g /etc/netplan/01-netcfg.yaml"]
  // }

  
  provisioner "file" {
  source      = ".ssh/id_ed25519.pub"
  destination = "/tmp/id_ed25519.pub"
}

# Provision the VM with the copied key
provisioner "shell" {
  inline = [
    "mkdir -p /home/ubuntu/.ssh",
    "chmod 700 /home/ubuntu/.ssh",
    "cat /tmp/id_ed25519.pub >> /home/ubuntu/.ssh/authorized_keys",
    "chmod 600 /home/ubuntu/.ssh/authorized_keys",
    "chown -R ubuntu:ubuntu /home/ubuntu/.ssh"
  ]
}

  provisioner "shell" {
    environment_vars  = [
      "DEBIAN_FRONTEND=noninteractive", 
      "UPDATE=${var.update}", 
      "SSH_USERNAME=${var.ssh_username}", 
      "SSH_PASSWORD=${var.ssh_password}", 
      "http_proxy=${var.http_proxy}", 
      "https_proxy=${var.https_proxy}", 
      "no_proxy=${var.no_proxy}"
    ]
    execute_command   = "echo '${var.ssh_password}'|{{ .Vars }} sudo -E -S bash '{{ .Path }}'"
    expect_disconnect = true
    scripts           = [
      "script/wait-for-ssh.sh", 
      "script/update.sh", 
      "script/cleanup.sh",
      "script/ssh.sh"
    ]
  }


}
